# Generated by Django 3.2.9 on 2021-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pincode_of_shop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('J', 'Jeans'), ('CM', 'Covid Medicine'), ('G', 'Grocery'), ('MK', 'Mask'), ('S', 'Sanitizer'), ('K', 'KitchenEssential')], max_length=2),
        ),
    ]
