# Generated by Django 3.2.9 on 2021-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
