# Generated by Django 4.0 on 2022-04-15 22:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0005_auto_20211108_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Pending', 'Pending')], default='Pending', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carts',
        ),
        migrations.RemoveField(
            model_name='pickorderplaced',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pickorderplaced',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pickorderplaced',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pincode_of_shop',
            new_name='eligibility',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='product',
            name='dateofevent',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('H', 'Hackathons'), ('C', 'Courses'), ('I', 'Internships'), ('S', 'Scholarships'), ('CE', 'CulEvents')], max_length=2),
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='PickOrderPlaced',
        ),
        migrations.AddField(
            model_name='eventregistered',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='eventregistered',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='eventregistered',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
