# Generated by Django 4.0 on 2022-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_mini_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateofevent',
            field=models.DateTimeField(),
        ),
    ]
